package jspha.alder.vdom.syntax

/**
  * Created by tel on 5/31/16.
  */
class HtmlAttrs[El, Mod](syntax: Internal[El, Mod]) {

  import syntax.makeJsValueMod
  import syntax.makeBooleanValueMod

  def dataAttr(name: String)(value: String): Mod =
    makeJsValueMod("data-" + name)(value)
  def ariaAttr(name: String)(value: String): Mod =
    makeJsValueMod("data-" + name)(value)

  // boolean valued attrs (present or absent)
  def allowFullScreen(value: Boolean): Mod = makeBooleanValueMod("allowFullScreen")(value)
  def allowTransparency(value: Boolean): Mod = makeBooleanValueMod("allowTransparency")(value)
  def async(value: Boolean): Mod = makeBooleanValueMod("async")(value)
  def autoCapitalize(value: Boolean): Mod = makeBooleanValueMod("autoCapitalize")(value)
  def autoComplete(value: Boolean): Mod = makeBooleanValueMod("autoComplete")(value)
  def autoCorrect(value: Boolean): Mod = makeBooleanValueMod("autoCorrect")(value)
  def autoFocus(value: Boolean): Mod = makeBooleanValueMod("autoFocus")(value)
  def autoPlay(value: Boolean): Mod = makeBooleanValueMod("autoPlay")(value)
  def autoSave(value: Boolean): Mod = makeBooleanValueMod("autoSave")(value)
  def capture(value: Boolean): Mod = makeBooleanValueMod("capture")(value)
  def checked(value: Boolean): Mod = makeBooleanValueMod("checked")(value)
  def contentEditable(value: Boolean): Mod = makeBooleanValueMod("contentEditable")(value)
  def controls(value: Boolean): Mod = makeBooleanValueMod("controls")(value)
  def defaultChecked(value: Boolean): Mod = makeBooleanValueMod("defaultChecked")(value)
  def defer(value: Boolean): Mod = makeBooleanValueMod("defer")(value)
  def disabled(value: Boolean): Mod = makeBooleanValueMod("disabled")(value)
  def formNoValidate(value: Boolean): Mod = makeBooleanValueMod("formNoValidate")(value)
  def hidden(value: Boolean): Mod = makeBooleanValueMod("hidden")(value)
  def multiple(value: Boolean): Mod = makeBooleanValueMod("multiple")(value)
  def muted(value: Boolean): Mod = makeBooleanValueMod("muted")(value)
  def noValidate(value: Boolean): Mod = makeBooleanValueMod("noValidate")(value)
  def readOnly(value: Boolean): Mod = makeBooleanValueMod("readOnly")(value)
  def required(value: Boolean): Mod = makeBooleanValueMod("required")(value)
  def reversed(value: Boolean): Mod = makeBooleanValueMod("reversed")(value)
  def scoped(value: Boolean): Mod = makeBooleanValueMod("scoped")(value)
  def seamless(value: Boolean): Mod = makeBooleanValueMod("seamless")(value)
  def selected(value: Boolean): Mod = makeBooleanValueMod("selected")(value)

  // "true" and "false" attributes
  def spellCheck(value: Boolean): Mod = makeJsValueMod("spellCheck")(
    if (value) "true" else "false"
  )
  def draggable(value: Boolean): Mod = makeJsValueMod("draggable")(
    if (value) "true" else "false"
  )

  // "Freeform" attributes
  def `class`(value: String): Mod = syntax.className(value)
  def `for`(value: String): Mod = makeJsValueMod("htmlFor")(value)
  def `type`(value: String): Mod = makeJsValueMod("type")(value)
  def about(value: String): Mod = makeJsValueMod("about")(value)
  def accept(value: String): Mod = makeJsValueMod("accept")(value)
  def acceptCharset(value: String): Mod = makeJsValueMod("acceptCharset")(value)
  def accessKey(value: String): Mod = makeJsValueMod("accessKey")(value)
  def action(value: String): Mod = makeJsValueMod("action")(value)
  def alt(value: String): Mod = makeJsValueMod("alt")(value)
  def cellPadding(value: String): Mod = makeJsValueMod("cellPadding")(value)
  def cellSpacing(value: String): Mod = makeJsValueMod("cellSpacing")(value)
  def challenge(value: String): Mod = makeJsValueMod("challenge")(value)
  def charSet(value: String): Mod = makeJsValueMod("charSet")(value)
  def cite(value: String): Mod = makeJsValueMod("cite")(value)
  def classID(value: String): Mod = makeJsValueMod("classID")(value)
  def colSpan(value: String): Mod = makeJsValueMod("colSpan")(value)
  def color(value: String): Mod = makeJsValueMod("color")(value)
  def cols(value: String): Mod = makeJsValueMod("cols")(value)
  def content(value: String): Mod = makeJsValueMod("content")(value)
  def contextMenu(value: String): Mod = makeJsValueMod("contextMenu")(value)
  def coords(value: String): Mod = makeJsValueMod("coords")(value)
  def crossOrigin(value: String): Mod = makeJsValueMod("crossOrigin")(value)
  def data(value: String): Mod = makeJsValueMod("data")(value)
  def datatype(value: String): Mod = makeJsValueMod("datatype")(value)
  def dateTime(value: String): Mod = makeJsValueMod("dateTime")(value)
  def default(value: String): Mod = makeJsValueMod("default")(value)
  def dir(value: String): Mod = makeJsValueMod("dir")(value)
  def download(value: String): Mod = makeJsValueMod("download")(value)
  def encType(value: String): Mod = makeJsValueMod("encType")(value)
  def form(value: String): Mod = makeJsValueMod("form")(value)
  def formAction(value: String): Mod = makeJsValueMod("formAction")(value)
  def formEncType(value: String): Mod = makeJsValueMod("formEncType")(value)
  def formMethod(value: String): Mod = makeJsValueMod("formMethod")(value)
  def formTarget(value: String): Mod = makeJsValueMod("formTarget")(value)
  def frameBorder(value: String): Mod = makeJsValueMod("frameBorder")(value)
  def headers(value: String): Mod = makeJsValueMod("headers")(value)
  def height(value: String): Mod = makeJsValueMod("height")(value)
  def high(value: String): Mod = makeJsValueMod("high")(value)
  def href(value: String): Mod = makeJsValueMod("href")(value)
  def hrefLang(value: String): Mod = makeJsValueMod("hrefLang")(value)
  def htmlFor(value: String): Mod = makeJsValueMod("htmlFor")(value)
  def httpEquiv(value: String): Mod = makeJsValueMod("httpEquiv")(value)
  def icon(value: String): Mod = makeJsValueMod("icon")(value)
  def id(value: String): Mod = makeJsValueMod("id")(value)
  def inlist(value: String): Mod = makeJsValueMod("inlist")(value)
  def inputMode(value: String): Mod = makeJsValueMod("inputMode")(value)
  def integrity(value: String): Mod = makeJsValueMod("integrity")(value)
  def is(value: String): Mod = makeJsValueMod("is")(value)
  def itemID(value: String): Mod = makeJsValueMod("itemID")(value)
  def itemProp(value: String): Mod = makeJsValueMod("itemProp")(value)
  def itemRef(value: String): Mod = makeJsValueMod("itemRef")(value)
  def itemScope(value: String): Mod = makeJsValueMod("itemScope")(value)
  def itemType(value: String): Mod = makeJsValueMod("itemType")(value)
  def keyParams(value: String): Mod = makeJsValueMod("keyParams")(value)
  def keyType(value: String): Mod = makeJsValueMod("keyType")(value)
  def kind(value: String): Mod = makeJsValueMod("kind")(value)
  def label(value: String): Mod = makeJsValueMod("label")(value)
  def lang(value: String): Mod = makeJsValueMod("lang")(value)
  def list(value: String): Mod = makeJsValueMod("list")(value)
  def loop(value: String): Mod = makeJsValueMod("loop")(value)
  def low(value: String): Mod = makeJsValueMod("low")(value)
  def manifest(value: String): Mod = makeJsValueMod("manifest")(value)
  def marginHeight(value: String): Mod = makeJsValueMod("marginHeight")(value)
  def marginWidth(value: String): Mod = makeJsValueMod("marginWidth")(value)
  def max(value: String): Mod = makeJsValueMod("max")(value)
  def maxLength(value: String): Mod = makeJsValueMod("maxLength")(value)
  def media(value: String): Mod = makeJsValueMod("media")(value)
  def mediaGroup(value: String): Mod = makeJsValueMod("mediaGroup")(value)
  def method(value: String): Mod = makeJsValueMod("method")(value)
  def min(value: String): Mod = makeJsValueMod("min")(value)
  def minLength(value: String): Mod = makeJsValueMod("minLength")(value)
  def name(value: String): Mod = makeJsValueMod("name")(value)
  def nonce(value: String): Mod = makeJsValueMod("nonce")(value)
  def open(value: String): Mod = makeJsValueMod("open")(value)
  def optimum(value: String): Mod = makeJsValueMod("optimum")(value)
  def pattern(value: String): Mod = makeJsValueMod("pattern")(value)
  def placeholder(value: String): Mod = makeJsValueMod("placeholder")(value)
  def poster(value: String): Mod = makeJsValueMod("poster")(value)
  def prefix(value: String): Mod = makeJsValueMod("prefix")(value)
  def preload(value: String): Mod = makeJsValueMod("preload")(value)
  def profile(value: String): Mod = makeJsValueMod("profile")(value)
  def property(value: String): Mod = makeJsValueMod("property")(value)
  def radioGroup(value: String): Mod = makeJsValueMod("radioGroup")(value)
  def rel(value: String): Mod = makeJsValueMod("rel")(value)
  def resource(value: String): Mod = makeJsValueMod("resource")(value)
  def results(value: String): Mod = makeJsValueMod("results")(value)
  def role(value: String): Mod = makeJsValueMod("role")(value)
  def rowSpan(value: String): Mod = makeJsValueMod("rowSpan")(value)
  def rows(value: String): Mod = makeJsValueMod("rows")(value)
  def sandbox(value: String): Mod = makeJsValueMod("sandbox")(value)
  def scope(value: String): Mod = makeJsValueMod("scope")(value)
  def security(value: String): Mod = makeJsValueMod("security")(value)
  def shape(value: String): Mod = makeJsValueMod("shape")(value)
  def size(value: String): Mod = makeJsValueMod("size")(value)
  def sizes(value: String): Mod = makeJsValueMod("sizes")(value)
  def span(value: String): Mod = makeJsValueMod("span")(value)
  def src(value: String): Mod = makeJsValueMod("src")(value)
  def srcDoc(value: String): Mod = makeJsValueMod("srcDoc")(value)
  def srcLang(value: String): Mod = makeJsValueMod("srcLang")(value)
  def srcSet(value: String): Mod = makeJsValueMod("srcSet")(value)
  def start(value: String): Mod = makeJsValueMod("start")(value)
  def step(value: String): Mod = makeJsValueMod("step")(value)
  def summary(value: String): Mod = makeJsValueMod("summary")(value)
  def tabIndex(value: String): Mod = makeJsValueMod("tabIndex")(value)
  def target(value: String): Mod = makeJsValueMod("target")(value)
  def title(value: String): Mod = makeJsValueMod("title")(value)
  def typeof(value: String): Mod = makeJsValueMod("typeof")(value)
  def useMap(value: String): Mod = makeJsValueMod("useMap")(value)
  def value(value: String): Mod = makeJsValueMod("value")(value)
  def defaultValue(value: String): Mod = makeJsValueMod("defaultValue")(value)
  def vocab(value: String): Mod = makeJsValueMod("vocab")(value)
  def width(value: String): Mod = makeJsValueMod("width")(value)
  def wmode(value: String): Mod = makeJsValueMod("wmode")(value)
  def wrap(value: String): Mod = makeJsValueMod("wrap")(value)

}
